:base_uri: http://www50.atwiki.jp/imas_ml/pages
:page_list:
  - :page_id: 206
    :table_num: 10
  - :page_id: 205
    :table_num: 10
  - :page_id: 204
    :table_num: 10
  - :page_id: 203
    :table_num: 10
  - :page_id: 208
    :table_num: 10
  - :page_id: 210
    :table_num: 10
  - :page_id: 216
    :table_num: 10
  - :page_id: 217
    :table_num: 5
